Repository mixmoe/HibiAPI, pull requests merged in 2021-01, with the labels that each got.

#6 完成Bilibili API
  .vscode/settings.json
  api/bilibili/__init__.py
  api/bilibili/api/__init__.py
  api/bilibili/api/base.py
  api/bilibili/api/v2.py
  api/bilibili/api/v3.py
  api/pixiv/net.py
  app/__init__.py
  app/bilibili/__init__.py
  app/bilibili/v2.py
  app/bilibili/v3.py
  app/pixiv.py
  configs/bilibili.default.yml
  configs/general.default.yml
  pyproject.toml
  utils/config.py
  utils/decorators.py
  utils/exceptions.py
  utils/utils.py
Labels: enhancement

#7 添加测试
  .github/workflows/test.yml
  .vscode/settings.json
  README.md
  app/bilibili/v3.py
  app/pixiv.py
  configs/pixiv.default.yml
  main.py
  poetry.lock
  pyproject.toml
  requirements.txt
  test/__init__.py
  test/test_bilibili.py
  test/test_pixiv.py
  utils/config.py
  utils/log.py
Labels: enhancement

#10 完成网易云音乐API
  .github/logo.svg
  .vscode/settings.json
  Dockerfile
  README.md
  api/__init__.py
  api/bilibili/api/base.py
  api/bilibili/api/v2.py
  api/bilibili/api/v3.py
  api/netease/__init__.py
  api/netease/api.py
  api/netease/constants.py
  api/netease/net.py
  api/pixiv/api.py
  api/pixiv/net.py
  app/__init__.py
  app/netease.py
  configs/general.default.yml
  configs/netease.default.yml
  main.py
  poetry.lock
  pyproject.toml
  requirements.txt
  test/test_netease.py
  utils/config.py
  utils/decorators.py
  utils/exceptions.py
  utils/log.py
Labels: enhancement

#14 完成百度贴吧API
  .vscode/settings.json
  README.md
  api/tieba/__init__.py
  api/tieba/api.py
  api/tieba/net.py
  app/routes/__init__.py
  app/routes/tieba.py
  test/test_tieba.py
Labels: enhancement

#16 🔧 补全网易云测试用例
  test/test_netease.py
Labels: test

#20 修复问题，补全文档
  api/pixiv/api.py
  app/routes/netease.py
  app/routes/pixiv.py
  test/test_pixiv.py
Labels: bug, documentation
